# Generated by Django 5.0.1 on 2024-02-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product_Mst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Product_Subcat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_price", models.FloatField()),
                ("product_image", models.ImageField(upload_to="Product_images")),
                ("product_model", models.CharField(max_length=20)),
                ("product_ram", models.CharField(max_length=20)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.product_mst",
                    ),
                ),
            ],
        ),
    ]
