# Generated by Django 5.0.1 on 2024-03-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product_subcat",
            name="product_image",
        ),
    ]
