# Generated by Django 5.0.1 on 2024-03-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_product_subcat_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_subcat",
            name="product_image",
            field=models.ImageField(default=1, upload_to="Product_images"),
            preserve_default=False,
        ),
    ]
